CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

TOKEN_FOR_MULTIPLE_CHOICE = "<multiple_choice>"
TOKEN_FOR_LONG_ANSWER = "<long_answer>"
TOKEN_FOR_SHORT_ANSWER = "<short_answe>"
TOKEN_FOR_REPORT_GENERATION = "<report_generation>"


